### ISSUE TITLE
Readme doesn't contain any mention of has_preferences

### ISSUE THREAD

**Issue by jbwl** [mubi/user_preferences#3]
The current readme or docs do not contain any hint how to get started with this gem. Specifically, it is mentioned nowhere that a model needs to have

`has_preferences`

declared.  I was able to figure this out by looking at the code, but maybe I'm missing other essential steps?

**Comment by lazyatom** [comment]
Hi @jbwl - I've just added a section that should hopefully provide the context you were missing. Let me know if you think it could be clearer :-)

**Comment by jbwl** [comment]
Yes, I think that fixes it! Thank you.
